name: chance_dart_cli
description: Random generator helper for Dart
version: 0.0.1-beta
homepage: https://github.com/Yczar/chance-dart

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  args: ^2.3.1
  chance_dart: ^0.0.1-beta
  mason_logger: ^0.2.0
  pub_updater: ^0.2.1

dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  build_version: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ">=3.1.0 <5.0.0"

executables:
  chance_dart_cli:
  chance_dart:
  chance: